[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mcd_tareagrupowhatsapp"
version = "0.0.1"
description = "An\u00e1lisis exploratorio de datos dsobre mensajes de un grupo de whatsapp"
authors = [
  { name = "Universidad de Sonora" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "==3.13.2"


[tool.ruff]
line-length = 99
src = ["mcd_tareagrupowhatsapp"]
include = ["pyproject.toml", "mcd_tareagrupowhatsapp/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["mcd_tareagrupowhatsapp"]
force-sort-within-sections = true

